storeType: column
columns:
  id:
    type: varchar
    length: 255
    allowNull: !!bool false
  _source:
    type: JSON
    allowNull: !!bool false
  timestamp:
    type: date
  tenantId:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'tenant', 'id')
  virtualEnv:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'virtualEnv')

keys:
  clustered: id
  timestamp:
    columns: ['timestamp']
    type: HASH
