meta:
  key: ACH_Payment
encryptedPaths:
  - receiver.accountNumber
  - receiver.routingNumber
  - receiver.identification
  - institutions.destination.routingNumber
persistence:
  table:
    name: ACH_PAYMENT
    database: payment
    schema:
      $ref: schema.yaml
    view:
      default:
        $ref: view.yaml
      settlement:
        $ref: settlement.yaml
      withfilename:
        $ref: viewWithFileName.yaml
  topic:
    name: ach.payment
    partitions: 3
    replicationFactor: 3
pipelines:
  streamliner:
    replicas: 3
name: ACH Payment
