storeType: row
columns:
  id:
    type: varchar
    length: 255
    allowNull: !!bool "false"
  _source:
    type: json
    allowNull: !!bool "false"
  processed:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'processed')
keys:
  primary: id
