storeType: row
columns:
  id:
    type: varchar
    length: 255
    allowNull: !!bool "false"
  _source:
    type: json
    allowNull: !!bool "false"
  status:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'status')
  filename:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'fileName')
  batchId:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'batchId')
  destinationId:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'destinationId')
  createdEST:
    type: varchar
    length: 255
    path: CONVERT_TZ(JSON_EXTRACT_STRING (`_source`,'created'), 'GMT', 'America/New_York')
  modifiedEST:
      type: varchar
      length: 255
      path: CONVERT_TZ(JSON_EXTRACT_STRING (`_source`,'modified'), 'GMT', 'America/New_York')
keys:
  primary: id
