storeType: row
columns:
  id:
    type: varchar
    length: 255
    allowNull: !!bool 'false'
  _source:
    type: json
    allowNull: !!bool 'false'
  error:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'error')
  request:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'request')
  reject:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'reject')
keys:
  primary: id
