storeType: row
columns:
  id:
    type: varchar
    length: 255
    allowNull: !!bool 'false'
  _source:
    type: json
    allowNull: !!bool 'false'
  status:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'status')
  singleMessage:
    type: bool
    path: case when coalesce(JSON_EXTRACT_STRING(`_source`, 'singleMessage'), 'false') = 'true' then 1 else 0 end
  created:
    type: datetime
    path: JSON_EXTRACT_STRING(`_source`, 'created')
keys:
  primary: id
