storeType: row
columns:
  id:
    type: varchar
    length: 255
    allowNull: !!bool 'false'
  _source:
    type: json
    allowNull: !!bool 'false'
  status:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'status')
  singleMessage:
    type: varchar
    length: 6
    path: coalesce(JSON_EXTRACT_STRING(`_source`, 'singleMessage'), 'false')
keys:
  primary: id
