storeType: row
columns:
  id:
    type: varchar
    length: 255
    allowNull: !!bool 'false'
  _source:
    type: json
    allowNull: !!bool 'false'
  status:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'status')
  cutoff:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'cutoff')
keys:
  primary: id
