storeType: row
columns:
  id:
    type: varchar
    length: 255
    allowNull: !!bool 'false'
  _source:
    type: json
    allowNull: !!bool 'false'
  externalId:
    type: varchar
    length: 255
    path: _source::$externalId
  status:
    type: varchar
    length: 255
    path: _source::$status
  tenderType:
    type: varchar
    length: 255
    path: _source::$tenderType
  effectiveDate:
    type: datetime
    path: _source::$effectiveDate
  companyId:
    type: varchar
    length: 255
    path: _source::$companyId
  standardEntryClassCode:
    type: varchar
    length: 255
    path: _source::$standardEntryClassCode
keys:
  primary: id