storeType: row
columns:
  id:
    type: varchar
    length: 255
    allowNull: !!bool 'false'
  _source:
    type: json
    allowNull: !!bool 'false'
  externalId:
    type: varchar
    allowNull: !!bool 'false'
  status:
    type: varchar
    allowNull: !!bool 'false'
  tenderType:
    type: varchar
    allowNull: !!bool 'false'
  parentNachaId:
    type: varchar
    allowNull: !!bool 'false'
  effectiveDate:
    type: timestamp
    allowNull: !!bool 'false'
  companyId:
    type: varchar
    allowNull: !!bool 'false'
  standardEntryClassCode:
    type: varchar
    allowNull: !!bool 'false'
keys:
  primary: id
  shard: ['id','externalId','status', 'tenderType','parentNachaId','effectiveDate','companyId','standardEntryClassCode']