storeType: row
columns:
  id:
    type: varchar
    length: 255
    allowNull: !!bool 'false'
  _source:
    type: json
    allowNull: !!bool 'false'
  externalId:
    type: varchar
    length: 255
    path: _source::$externalId
keys:
  primary: id