storeType: row
columns:
  id:
    type: varchar
    length: 255
    allowNull: !!bool 'false'
  _source:
    type: json
    allowNull: !!bool 'false'
  tenantId:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'tenantId')
  service:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'service')
  virtualEnv:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'virtualEnv')
  replicationGroup:
    type: varchar
    length: 255
    path: JSON_EXTRACT_STRING(`_source`, 'replicationGroup')
keys:
  primary: id
